name: Dispatch All Device Builds
on:
  workflow_dispatch:

jobs:
  dispatch:
    name: Trigger ${{ matrix.workflow }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - workflow: ace2.yml
            CPU: sm8475
            FEIL: oneplus_ace2_v
            CPUD: taro
          - workflow: ace2pro.yml
            CPU: sm8550
            FEIL: oneplus_ace2pro_v
            CPUD: kalama
          - workflow: ace3.yml
            CPU: sm8550
            FEIL: oneplus_ace3_v
            CPUD: kalama
          - workflow: ace3Pro.yml
            CPU: sm8650
            FEIL: oneplus_ace3_pro_v
            CPUD: pineapple
          - workflow: ace3v.yml
            CPU: sm7675
            FEIL: oneplus_ace_3v_v
            CPUD: pineapple
          - workflow: ace5.yml
            CPU: sm8650
            FEIL: oneplus_ace5
            CPUD: pineapple
          - workflow: ace5pro整合.yml
            CPU: sm8750
            FEIL: oneplus_ace5_pro
            CPUD: sun
          - workflow: acePro.yml
            CPU: sm8475
            FEIL: oneplus_ace_pro_v
            CPUD: taro
          - workflow: gt5pro.yml
            CPU: sm8650
            FEIL: gt5pro
            CPUD: pineapple
          - workflow: OnePlus11.yml
            CPU: sm8550
            FEIL: oneplus_11_v
            CPUD: kalama
          - workflow: oneplus12.yml
            CPU: sm8650
            FEIL: oneplus12_v
            CPUD: pineapple
          - workflow: oneplus12r.yml
            CPU: sm8550
            FEIL: oneplus_12r_v
            CPUD: kalama
          - workflow: oneplus13整合.yml
            CPU: sm8750
            FEIL: oneplus_13
            CPUD: sun
          - workflow: padpro.yml
            CPU: sm8650
            FEIL: oneplus_pad2_v
            CPUD: pineapple

    steps:
      - name: Trigger ${{ matrix.workflow }}
        uses: peter-evans/workflow-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          workflow: ${{ matrix.workflow }}
          ref: ${{ github.ref_name }}
          inputs: |
            CPU: ${{ matrix.CPU }}
            FEIL: ${{ matrix.FEIL }}
            CPUD: ${{ matrix.CPUD }}
