name: 取消所有工作流
on:
  workflow_dispatch:

jobs:
  trigger-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger all workflows via REST API (with cancellation)
        run: |
          workflows=(
            "ace2.yml"
            "ace2pro.yml"
            "ace3.yml"
            "ace3Pro.yml"
            "ace3v.yml"
            "ace5.yml"
            "ace5pro整合.yml"
            "acePro.yml"
            "OnePlus11.yml"
            "oneplus12.yml"
            "oneplus12r.yml"
            "oneplus13整合.yml"
            "oneplus13t整合.yml"
            "padpro.yml"
          )

          for wf in "${workflows[@]}"; do
            echo "Checking and cancelling any in-progress runs of $wf..."
            
            # 获取 workflow_id
            workflow_id=$(curl -s -H "Authorization: Bearer ${{ secrets.PAT }}" \
              https://api.github.com/repos/${{ github.repository }}/actions/workflows \
              | jq ".workflows[] | select(.path == \".github/workflows/$wf\") | .id")

            # 获取进行中的运行
            run_ids=$(curl -s -H "Authorization: Bearer ${{ secrets.PAT }}" \
              "https://api.github.com/repos/${{ github.repository }}/actions/workflows/$workflow_id/runs?status=in_progress" \
              | jq ".workflow_runs[] | select(.head_branch==\"main\") | .id")

            for run_id in $run_ids; do
              echo "Cancelling run $run_id of $wf..."
              curl -s -X POST -H "Authorization: Bearer ${{ secrets.PAT }}" \
                "https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id/cancel"
            done

            echo "Dispatching $wf..."
            curl -X POST "https://api.github.com/repos/${{ github.repository }}/actions/workflows/$wf/dispatches" \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.PAT }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -d '{"ref":"main"}'
          done
