name: 运行所有工作流
on:
  workflow_dispatch:

jobs:
  trigger-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger all workflows via REST API
        run: |
          workflows=(
            "ace2.yml"
            "ace2pro.yml"
            "ace3.yml"
            "ace3Pro.yml"
            "ace3v.yml"
            "ace5.yml"
            "ace5pro整合.yml"
            "acePro.yml"
            "OnePlus11.yml"
            "oneplus12.yml"
            "oneplus12r.yml"
            "oneplus13整合.yml"
            "oneplus13t整合.yml"
            "padpro.yml"
          )

          for wf in "${workflows[@]}"; do
            echo "Dispatching $wf..."
            curl -X POST "https://api.github.com/repos/${{ github.repository }}/actions/workflows/$wf/dispatches" \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.PAT }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -d '{"ref":"main"}'
          done
